### ISSUE TITLE
SNR = ?

### ISSUE THREAD

**Issue by trebmuh** [lucianodato/noise-repellent#25]
Hey @lucianodato , I'm just wondering if I'm right with assuming that SNR = **S**pectral **N**oise **R**eduction. If so, I then wonder why does the "SNR" has been translated to "S/R" in the Spanish translation [here](https://github.com/lucianodato/noise-repellent/blob/master/nrepel.ttl.in#L69).

**Comment by lucianodato** [comment]
SNR usually refers "signal to noise ratio" in engineering terma and there's​ no direct translation to spanish for that. So in spanish terms you would normally use signal vs noise so that is why I've used S/N. That slider increase the influence of the local SNR in the suppression rule that the plugin is using. I already have a manual in spanish and I'm working on an english translation. Would you like it to be uploaded to this repo? Maybe you could translate it.

**Comment by trebmuh** [comment]
Thanks for the answer @lucianodato .
Yes please, upload the manual in the repo then I'll be able and happy to translate it in French. It's awesome to see a dev taking care of the documentation, thanks for that !

**Comment by lucianodato** [comment]
Is it an odt file sufficient or convenient for this? I don't really know how to proceed

**Comment by lucianodato** [comment]
Excellent! I will upload it when I finish it

**Comment by trebmuh** [comment]
Nice. Feel free to ping me when it's ready.
