### ISSUE TITLE
Wrong translation strings being used when loading it in Reaper in Linux

### ISSUE THREAD

**Issue by lucianodato** [lucianodato/noise-repellent#81]
As reported here https://forum.cockos.com/showthread.php?p=2483093

**Comment by lucianodato** [comment]
This is currently reported as a reaper bug here https://forum.cockos.com/showthread.php?t=258123. It could be distro related also

**Comment by justinfrankel** [comment]
This is definitely a REAPER bug and it will be fixed in 6.37rc6 and 6.37 (to be released in the next couple of weeks).

If you want to work around the bug in earlier versions of REAPER, the port names could be listed with the non-localized string last, e.g.:

` lv2:name "Compensacion de umbrales"@es , "Décalage des seuils"@fr ,  "Thresholds offset" ;` 

which would default to English on REAPER 6.36 and earlier. Sorry for our bug!

**Comment by lucianodato** [comment]
Thanks for the quick notice Justin! You are the man! @trebmuh FYI!

**Comment by trebmuh** [comment]
A-WE-SO-ME guys :+1:
